src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\Column(length: 255)]
    private ?string $profilePicture = null;

    /**
     * @var Collection<int, Post>
     */
    #[ORM\OneToMany(targetEntity: Post::class, mappedBy: 'user')]
    private Collection $post;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'user')]
    private Collection $comment;

    public function __construct()
    {
        $this->post = new ArrayCollection();
        $this->comment = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->roles = ["ROLE_VISITEUR"];
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getFullName(): string
    {
    return $this->getFirstName() . ' ' . $this->getLastName();
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }
    #[ORM\PrePersist]
    public function setCreatedAt() : void
    {
        $this->createdAt = new \DateTime() ;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(string $profilePicture): static
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPost(): Collection
    {
        return $this->post;
    }

    public function addPost(Post $post): static
    {
        if (!$this->post->contains($post)) {
            $this->post->add($post);
            $post->setUser($this);
        }

        return $this;
    }

    public function removePost(Post $post): static
    {
        if ($this->post->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comment->contains($comment)) {
            $this->comment->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comment->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Category;
use Symfony\Component\Validator\Constraints as Asserts;


class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('title', TextType::class, [
            'label' => 'Titre',
            //new Asserts\NotBlank(),
        ])
        ->add('content', TextareaType::class, [
            'label' => 'Contenu',
        ])
        ->add('publishedAt', DateTimeType::class, [
            'label' => 'Date de publication',
            'widget' => 'single_text',
            'required' => false,
        ])
        ->add('picture', TextType::class, [
            'label' => 'URL de l’image',
            'required' => false,
        ])
        ->add('category', EntityType::class, [
            'class' => Category::class, // Utilise l'entité Category
            'choice_label' => 'name', // Affiche le nom des catégories
            'placeholder' => 'Sélectionnez une catégorie', // Optionnel
            'label' => 'Catégorie',
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

use App\Entity\Comment;
use App\Form\CommentType;

use App\Repository\PostRepository;
use App\Entity\Post;
use App\Form\PostType;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Category;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class PostController extends AbstractController
{
    #[Route('/post', name: 'post_list')]
    public function list(PostRepository $postRepository): Response
    {
        $posts = $postRepository->getAllPost();

        return $this->render('post/index.html.twig', [
            'posts' => $posts,
        ]);
    }

    #[Route('/category/{id}/posts', name: 'posts_by_category', requirements: ['id' => '\d+'])]
    public function postsByCategory(int $id, PostRepository $postRepository): Response
    {
        $posts = $postRepository->getPostsByCategory($id);

        return $this->render('post/posts_by_category.html.twig', [
            'posts' => $posts,
        ]);
    }

    #[Route('/post/{id}', name: 'post_show', requirements: ['id' => '\d+'])]
    public function show(
        int $id,
        PostRepository $postRepository,
        Request $request,
        EntityManagerInterface $entityManager
    ): Response {
        // Récupérer le post avec ses relations (commentaires et utilisateur)
        $post = $postRepository->getPostWithRelations($id);
    
        if (!$post) {
            throw $this->createNotFoundException("Le post avec l'ID $id n'existe pas.");
        }
    
        // Création du formulaire d'ajout de commentaire
        $comment = new Comment();
        $comment->setPost($post);
        $comment->setCreatedAt(new \DateTimeImmutable());
    
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($comment);
            $entityManager->flush();
    
            $this->addFlash('success', 'Commentaire ajouté avec succès.');
    
            // Redirection pour éviter la soumission multiple
            return $this->redirectToRoute('post_show', ['id' => $id]);
        }
    
        return $this->render('post/show.html.twig', [
            'post' => $post,
            'comments' => $post->getComment(), // Utiliser la méthode existante pour récupérer les commentaires
            'author' => $post->getUser(), // Récupérer l'auteur du post
            'form' => $form->createView(), // Passer le formulaire à la vue
        ]);
    }    

    #[Route('/post/{id}/add-comment', name: 'add_comment', methods: ['POST'])]
    #[IsGranted('ROLE_VISITEUR')]
    public function addComment(int $id, Request $request, PostRepository $postRepository, EntityManagerInterface $entityManager): Response
    {
        $post = $postRepository->find($id);

        if (!$post) {
            throw $this->createNotFoundException("Le post avec l'ID $id n'existe pas.");
        }

        $comment = new Comment();
        $comment->setPost($post);
        $comment->setCreatedAt(new \DateTimeImmutable());

        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('post_show', ['id' => $id]);
        }

        return $this->render('post/show.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/comment/{id}/delete', name: 'delete_comment', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function deleteComment(int $id, EntityManagerInterface $entityManager): Response
    {
        $comment = $entityManager->getRepository(Comment::class)->find($id);

        if (!$comment) {
            throw $this->createNotFoundException("Le commentaire avec l'ID $id n'existe pas.");
        }

        $entityManager->remove($comment);
        $entityManager->flush();

        $this->addFlash('success', 'Commentaire supprimé avec succès.');

        return $this->redirectToRoute('post_show', ['id' => $comment->getPost()->getId()]);
    }


    #[Route('/post/new', name: 'post_new')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PostType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $post = new Post();
            $post->setTitle($data['title']);
            $post->setContent($data['content']);
            $post->setPicture($data['picture']);
            $post->setPublishedAt($data['publishedAt']);
            $post->setCategory($data['category']);
            $post->setUser($this->getUser());

            $entityManager->persist($post);
            $entityManager->flush();

            $this->addFlash('success', 'Post ajouté avec succès.');
            
            return $this->redirectToRoute('post_list');
        }

        // Retourne la vue avec le formulaire pour tous les autres cas
        return $this->render('post/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }



    #[Route('/post/{id}/edit', name: 'post_edit')]
    public function edit(int $id, Request $request, EntityManagerInterface $entityManager): Response
    {
        $post = $entityManager->getRepository(Post::class)->find($id);

        if (!$post) {
            throw $this->createNotFoundException('Post non trouvé.');
        }

        $form = $this->createForm(PostType::class, [
            'title' => $post->getTitle(),
            'content' => $post->getContent(),
            'picture' => $post->getPicture(),
            'publishedAt' => $post->getPublishedAt(),
            'category' => $post->getCategory(),
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $post->setTitle($data['title']);
            $post->setContent($data['content']);
            $post->setPicture($data['picture']);
            $post->setPublishedAt($data['publishedAt']);
            $post->setCategoryId($data['category']);

            $entityManager->flush();

            $this->addFlash('success', 'Post modifié avec succès.');

            return $this->redirectToRoute('post_list');
        }

        return $this->render('post/edit.html.twig', [
            'form' => $form->createView(),
            'post' => $post,
        ]);
    }


    #[Route('/post/{id}/delete', name: 'post_delete', methods: ['POST'])]
    public function delete(int $id, Request $request, EntityManagerInterface $entityManager): Response
    {
        $post = $entityManager->getRepository(Post::class)->find($id);

        if (!$post) {
            throw $this->createNotFoundException('Post non trouvé.');
        }

        if ($this->isCsrfTokenValid('delete' . $post->getId(), $request->request->get('_token'))) {
            $entityManager->remove($post);
            $entityManager->flush();

            $this->addFlash('success', 'Post supprimé avec succès.');
        }

        return $this->redirectToRoute('post_list');
    }

}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Modifier le Post</h1>
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">Modifier</button>
    {{ form_end(form) }}
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des posts{% endblock %}
        {% block body %}
            <h1>Liste des posts</h1>
            {% if is_granted('ROLE_ADMIN')%}
            <a href="/post/new" class="btn btn-success">Créer un nouveau post</a>
            {% endif %}
            <div class="row">
            {% for post in posts %}
            <div class="col-3 text-center d-flex align-items-stretch">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <img class="card-img w-100 h-75" src="{{ post.picture }}" alt="{{ post.title }}">
                        <a class="btn btn-primary w-100" href="{{ path('post_show', { id: post.id }) }}">Voir détails</a>
                    </div>
                </div>
            </div>
            {% else %}
        <p>No posts found in this category.</p>
        {% endfor %}
    </div>
        {% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h3 class="card-title mb-0 text-center">Ajouter un Post</h3>
                </div>
                <div class="card-body">
                    {{ form_start(form) }}
                        <div class="mb-3">
                            {{ form_label(form.title, 'Titre', { 'label_attr': { 'class': 'form-label' } }) }}
                            {{ form_widget(form.title, { 'attr': { 'class': 'form-control' } }) }}
                            {{ form_errors(form.title) }}
                        </div>
                        <div class="mb-3">
                            {{ form_label(form.content, 'Contenu', { 'label_attr': { 'class': 'form-label' } }) }}
                            {{ form_widget(form.content, { 'attr': { 'class': 'form-control' } }) }}
                            {{ form_errors(form.content) }}
                        </div>
                        <div class="mb-3">
                            {{ form_label(form.publishedAt, 'Date de publication', { 'label_attr': { 'class': 'form-label' } }) }}
                            {{ form_widget(form.publishedAt, { 'attr': { 'class': 'form-control' } }) }}
                            {{ form_errors(form.publishedAt) }}
                        </div>
                        <div class="mb-3">
                            {{ form_label(form.picture, 'URL de l’image', { 'label_attr': { 'class': 'form-label' } }) }}
                            {{ form_widget(form.picture, { 'attr': { 'class': 'form-control' } }) }}
                            {{ form_errors(form.picture) }}
                        </div>
                        <div class="mb-3">
                            {{ form_label(form.category, 'Catégorie', { 'label_attr': { 'class': 'form-label' } }) }}
                            {{ form_widget(form.category, { 'attr': { 'class': 'form-select' } }) }}
                            {{ form_errors(form.category) }}
                        </div>
                        <div class="text-center">
                            <button class="btn btn-success w-50">Ajouter</button>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/post/posts_by_category.html.twig
{% extends 'base.html.twig' %}

{% block title %}Posts by Category{% endblock %}

{% block body %}
    <h1>Posts in this Category</h1>
    {% if is_granted('ROLE_ADMIN')%}
    <a href="/post/new" class="btn btn-success">Créer un nouveau post</a>
    {% endif %}
    <div class="row">
            {% for post in posts %}
        <div class="col-3 text-center d-flex align-items-stretch w-25">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <img class="card-img w-100" src="{{ post.picture }}" alt="{{ post.title }}">
                        <a class="btn btn-primary w-100" href="{{ path('post_show', { id: post.id }) }}">Voir détails</a>
                    </div>
                </div>
            </div>
        {% else %}
        <p>No posts found in this category.</p>
        {% endfor %}
    </div>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">
        <h2>Détails du post</h2>
        <a class="btn btn-primary w-25" href="{{ path('post_list') }}">Retour à la liste</a>    
        <div class="text-center card shadow-sm">
            <div class="card-body w-25 mx-auto text-center d-flex justify-content-center flex-column">
                <h1 class="card-title">{{ post.title }}</h1>
                <img class="card-img" src="{{ post.picture }}" alt="{{ post.title }}">
                <p class="card-text">{{ post.content }}</p>
                {% if is_granted('ROLE_ADMIN')%}
                <form method="post" action="{{ path('post_delete', { id: post.id }) }}" onsubmit="return confirm('Êtes-vous sûr ?');">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
                    <button class="btn btn-danger">Supprimer</button>
                </form>
                {% endif %}
            </div>
        </div>
        <h2>Commentaires</h2>
        {% if comments|length > 0 %}
            <ul class="list-group">
                {% for comment in comments %}
                    <li class="list-group-item">
                        <h5><strong>Auteur :</strong> {{ author.fullName }}</h5>
                        {{ comment.createdAt|date('d/m/Y H:i') }} :
                        {{ comment.content }}
                        {% if is_granted('ROLE_ADMIN')%}
                        <form method="post" action="{{ path('delete_comment', { id: comment.id }) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce commentaire ?');">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
                            <button class="btn btn-danger btn-sm">Supprimer</button>
                        </form>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Aucun commentaire pour ce post.</p>
        {% endif %}
        {% if is_granted('ROLE_USER')%}
        <div class="container mt-4">
            <h2>Ajouter un commentaire</h2>
            {{ form_start(form) }}
                {{ form_row(form.content) }}
                <button class="btn btn-success mt-2">Ajouter</button>
            {{ form_end(form) }}
        </div>
        {% else %}
            {% if is_granted('ROLE_VISITEUR')%}
            <div class="container mt-4">
                <h5>Vous ne pouvez pas ajouter de commentaire</h5>
            </div>
            {% else %}
                <div class="container mt-4">
                    <h5>Vous devez être connécté pour ajouter un commentaire</h5>
                </div>
            {% endif %}
            <br>
            <br>
            <br>
        {% endif %}
    </div>
{% endblock %}